# Generated by Django 5.0.2 on 2024-02-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_models', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('vehicle_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.vehiclemake')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_year', models.IntegerField()),
                ('distance_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_unit', models.CharField(max_length=10)),
                ('carbon_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbon_lb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbon_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbon_mt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.vehiclemake')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleapp.vehiclemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='EmissionData',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
