# Generated by Django 5.0.2 on 2024-02-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0002_vehiclemake_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleestimate',
            name='vehicle_year',
        ),
    ]
