# Generated by Django 5.0.2 on 2024-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0003_remove_vehicleestimate_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleestimate',
            name='distance_unit',
            field=models.CharField(choices=[('mi', 'miles (mi)'), ('km', 'kilometers (km)')], max_length=2),
        ),
    ]
