# Generated by Django 5.0.2 on 2024-02-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0004_alter_vehicleestimate_distance_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleestimate',
            name='vehicle_year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
