# Generated by Django 5.0.2 on 2024-02-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0005_vehicleestimate_vehicle_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemake',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
