# Generated by Django 5.0.2 on 2024-02-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0006_alter_vehiclemake_id_alter_vehiclemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleestimate',
            name='distance_unit',
            field=models.CharField(choices=[('miles', 'mi'), ('kilometers', 'km')], max_length=20),
        ),
    ]
