# Generated by Django 5.0.2 on 2024-02-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleapp', '0007_alter_vehicleestimate_distance_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleestimate',
            name='distance_unit',
            field=models.CharField(choices=[('mi', 'miles'), ('km', 'kilometers')], max_length=20),
        ),
    ]
